// PWA Service Worker registration - shim for virtual module
// This is normally generated by vite-plugin-pwa at build time

export function registerSW(options: {
  onNeedRefresh?: () => void;
  onOfflineReady?: () => void;
  onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
  onRegisterError?: (error: unknown) => void;
} = {}) {
  const {
    onNeedRefresh = () => {},
    onOfflineReady = () => {},
    onRegistered = () => {},
    onRegisterError = () => {},
  } = options;

  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
    return {
      get needRefresh() { return { value: false }; },
      get offlineReady() { return { value: false }; },
      updateServiceWorker: () => Promise.resolve(),
    };
  }

  let needRefresh = false;
  let offlineReady = false;

  const updateServiceWorker = async () => {
    if (typeof window !== 'undefined') {
      window.location.reload();
    }
  };

  navigator.serviceWorker.ready.then((registration) => {
    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing;
      if (newWorker) {
        newWorker.addEventListener('statechange', () => {
          if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
            needRefresh = true;
            onNeedRefresh();
          }
        });
      }
    });
    onRegistered(registration);
  }).catch(onRegisterError);

  navigator.serviceWorker.addEventListener('controllerchange', () => {
    offlineReady = true;
    onOfflineReady();
  });

  return {
    get needRefresh() { return { value: needRefresh }; },
    get offlineReady() { return { value: offlineReady }; },
    updateServiceWorker,
  };
}